function generateId(){
    return Math.random();
}

export const cities = [
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
    { id: generateId(), cityName: 'New York', imageUrl: 'https://source.unsplash.com/800x600/?new-york-city' },
    { id: generateId(), cityName: 'Paris', imageUrl: 'https://source.unsplash.com/800x600/?paris' },
    { id: generateId(), cityName: 'Tokyo', imageUrl: 'https://source.unsplash.com/800x600/?tokyo' },
    { id: generateId(), cityName: 'London', imageUrl: 'https://source.unsplash.com/800x600/?london' },
    { id: generateId(), cityName: 'Rome', imageUrl: 'https://source.unsplash.com/800x600/?rome' },
    { id: generateId(), cityName: 'Sydney', imageUrl: 'https://source.unsplash.com/800x600/?sydney' },
    { id: generateId(), cityName: 'Berlin', imageUrl: 'https://source.unsplash.com/800x600/?berlin' },
    { id: generateId(), cityName: 'San Francisco', imageUrl: 'https://source.unsplash.com/800x600/?san-francisco' },
    { id: generateId(), cityName: 'Dubai', imageUrl: 'https://source.unsplash.com/800x600/?dubai' },
    { id: generateId(), cityName: 'Mumbai', imageUrl: 'https://source.unsplash.com/800x600/?mumbai' },
    { id: generateId(), cityName: 'Cape Town', imageUrl: 'https://source.unsplash.com/800x600/?cape-town' },
    { id: generateId(), cityName: 'Seoul', imageUrl: 'https://source.unsplash.com/800x600/?seoul' },
    { id: generateId(), cityName: 'Barcelona', imageUrl: 'https://source.unsplash.com/800x600/?barcelona' },
    { id: generateId(), cityName: 'Vienna', imageUrl: 'https://source.unsplash.com/800x600/?vienna' },
    { id: generateId(), cityName: 'Rio de Janeiro', imageUrl: 'https://source.unsplash.com/800x600/?rio-de-janeiro' },
    { id: generateId(), cityName: 'Toronto', imageUrl: 'https://source.unsplash.com/800x600/?toronto' },
    { id: generateId(), cityName: 'Amsterdam', imageUrl: 'https://source.unsplash.com/800x600/?amsterdam' },
    { id: generateId(), cityName: 'Prague', imageUrl: 'https://source.unsplash.com/800x600/?prague' },
    { id: generateId(), cityName: 'Bangkok', imageUrl: 'https://source.unsplash.com/800x600/?bangkok' },
    { id: generateId(), cityName: 'Los Angeles', imageUrl: 'https://source.unsplash.com/800x600/?los-angeles' },
    { id: generateId(), cityName: 'Singapore', imageUrl: 'https://source.unsplash.com/800x600/?singapore' },
    { id: generateId(), cityName: 'Istanbul', imageUrl: 'https://source.unsplash.com/800x600/?istanbul' },
    { id: generateId(), cityName: 'Shanghai', imageUrl: 'https://source.unsplash.com/800x600/?shanghai' },
    { id: generateId(), cityName: 'Chicago', imageUrl: 'https://source.unsplash.com/800x600/?chicago' },
    { id: generateId(), cityName: 'Dublin', imageUrl: 'https://source.unsplash.com/800x600/?dublin' },
    { id: generateId(), cityName: 'Stockholm', imageUrl: 'https://source.unsplash.com/800x600/?stockholm' },
    { id: generateId(), cityName: 'Mexico City', imageUrl: 'https://source.unsplash.com/800x600/?mexico-city' },
    { id: generateId(), cityName: 'Marrakech', imageUrl: 'https://source.unsplash.com/800x600/?marrakech' },
    { id: generateId(), cityName: 'Athens', imageUrl: 'https://source.unsplash.com/800x600/?athens' },
    { id: generateId(), cityName: 'Cairo', imageUrl: 'https://source.unsplash.com/800x600/?cairo' },
    { id: generateId(), cityName: 'Montreal', imageUrl: 'https://source.unsplash.com/800x600/?montreal' },
    { id: generateId(), cityName: 'Nairobi', imageUrl: 'https://source.unsplash.com/800x600/?nairobi' },
    { id: generateId(), cityName: 'Hong Kong', imageUrl: 'https://source.unsplash.com/800x600/?hong-kong' },
    { id: generateId(), cityName: 'Melbourne', imageUrl: 'https://source.unsplash.com/800x600/?melbourne' },
    { id: generateId(), cityName: 'Buenos Aires', imageUrl: 'https://source.unsplash.com/800x600/?buenos-aires' },
    { id: generateId(), cityName: 'Oslo', imageUrl: 'https://source.unsplash.com/800x600/?oslo' },
    { id: generateId(), cityName: 'Warsaw', imageUrl: 'https://source.unsplash.com/800x600/?warsaw' },
    { id: generateId(), cityName: 'Beijing', imageUrl: 'https://source.unsplash.com/800x600/?beijing' },
    { id: generateId(), cityName: 'Hanoi', imageUrl: 'https://source.unsplash.com/800x600/?hanoi' },
    { id: generateId(), cityName: 'Budapest', imageUrl: 'https://source.unsplash.com/800x600/?budapest' },
    { id: generateId(), cityName: 'Lisbon', imageUrl: 'https://source.unsplash.com/800x600/?lisbon' },
];


export const nameStatus  = [
    { name: 'John', status: 'Active' },
    { name: 'Alice', status: 'Inactive' },
    { name: 'Bob', status: 'Active' },
    { name: 'Eva', status: 'Active' },
    { name: 'Charlie', status: 'Inactive' },
    { name: 'Grace', status: 'Active' },
    { name: 'David', status: 'Inactive' },
    { name: 'Fiona', status: 'Active' },
    { name: 'Henry', status: 'Active' },
    { name: 'Isabel', status: 'Inactive' },
    { name: 'Jack', status: 'Active' },
    { name: 'Lily', status: 'Active' },
    { name: 'Mike', status: 'Inactive' },
    { name: 'Nora', status: 'Active' },
    { name: 'Oliver', status: 'Inactive' },
    { name: 'Pam', status: 'Active' },
    { name: 'Quinn', status: 'Active' },
    { name: 'Rachel', status: 'Inactive' },
    { name: 'Sam', status: 'Active' },
    { name: 'Tom', status: 'Inactive' }
];