export const indianPoliticsWords = [
    'Democracy',
    'Election',
    'Parliament',
    'Constituency',
    'Prime Minister',
    'President',
    'Governor',
    'Chief Minister',
    'Opposition',
    'Ruling Party',
    'Coalition',
    'Cabinet',
    'Legislation',
    'Policy',
    'Manifesto',
    'Vote',
    'Citizenship',
    'Lok Sabha',
    'Rajya Sabha',
    'State Assembly',
    'Constitution',
    'Secularism',
    'Reservation',
    'Federalism',
    'Union Territory',
    'Political Party',
    'Secular',
    'Communal',
    'Secession',
    'Judiciary',
    'Supreme Court',
    'High Court',
    'Judicial Review',
    'Emergency',
    'Censorship',
    'Political Ideology',
    'Caste Politics',
    'Dynasty Politics',
    'Corruption',
    'Bureaucracy',
    'Secular',
    'Constituent Assembly',
    'Foreign Policy',
    'Diplomacy',
    'Nationalism',
    'Patriotism',
    'Governance',
    'Accountability',
    'Constitutional Amendment',
    'Political Activism',
    'Reform',
    'Election Commission',
    'Electoral Process',
    'Political Science',
    'Alliance',
    'Human Rights',
    'Naxalism',
    'Maoism',
    'Censorship',
    'Political Dynasty',
    'Social Justice',
    'Political Spectrum',
    'Aadhaar',
    'Goods and Services Tax (GST)',
    'Demonetization',
    'Farm Bills',
    'Public Policy',
    'Bipartisanship',
    'Public Administration',
    'Reservation Policy',
    'Political Campaign',
    'Political Analyst',
    'Civic Duty',
    'National Integration',
    'Peacekeeping',
    'Cabinet Minister',
    'Shadow Cabinet',
    'Political Science',
    'Ombudsman',
    'Civic Engagement',
    'Political Dissent',
    'Public Opinion',
    'Panchayati Raj',
    'Electoral College',
    'Political Stability',
    'Economic Policy',
    'Government Transparency',
    'Legislative Assembly',
    'Legislative Council',
    'Secularism',
    'Civic Responsibility',
    'Public Service',
    'Political Allegiance',
    'Social Welfare',
    'Rule of Law',
    'Judicial Independence',
    'Voting Rights'
  ];
    